### ISSUE TITLE
"~0U" appearing in generated code

### ISSUE THREAD

**Issue by asmaloney** [bbredesen/vk-gen#13]
When I generate on macOS (for macos) I get the following:

```
ERRO[0001] Failed to format source file   error="exit status 2" goimports output="vk/external.go:10:37: expected ')', found U\nvk/external.go:11:1: expected declaration, found FALSE\n" path=vk/external.go
```

Generated:

```go
const (
REMAINING_3D_SLICES_EXT uint32 = (~0U)
FALSE uint32 = 0
TRUE uint32 = 1
...
```

**Comment by bbredesen** [comment]
What version of vk.xml are you using? Latest version I've generated against is 1.3.240 

I think this is a new symbol in a later patch version that has to be added to exceptions.json; reference the object at path "external.uint32_t.enums"

vk.xml defines a lot of things with C syntax. Instead of trying to parse and translate that at runtime, I just added them to exceptions.json with corrected Go syntax for the value.

**Comment by asmaloney** [comment]
> What version of vk.xml are you using?

It's extremely hard to figure out from the file itself 😆 It seems like an odd choice on their part not to make it human-readable somewhere.

I just grabbed it today using curl like you do in the docs, so I suppose it's 1.3.242?

**Comment by bbredesen** [comment]
It's definitely not as easy as it could be...feels like it should be in a comment block at the very top of the file. 

If you search for "VK_HEADER_VERSION" you'll see a bunch #defines with the version numbers. Looks like 1.3.242 is the current version at https://github.com/KhronosGroup/Vulkan-Docs/tree/main/xml

Update to exceptions.json for that value coming momentarily
